{
    "package2": [
        {
            "cvss_v2_score": 0.0,
            "cvss_v30_score": 0.0,
            "cvss_v31_score": 9.1,
            "cvss_v3_score": 9.1,
            "cvss_v3_severity": "CRITICAL",
            "description": "temp-description",
            "name": "CVE-456",
            "package_details": {
                "file_path": "usr/lib",
                "name": "package2",
                "package_manager": "PYTHONPKG",
                "release": null,
                "version": "1.2"
            },
            "package_name": "package2",
            "remediation": {
                "recommendation": {
                    "text": "None Provided"
                }
            },
            "severity": "CRITICAL",
            "source": "SNYK",
            "source_url": "https://temp-url",
            "status": "ACTIVE",
            "title": "CVE-456 - package2/package4",
            "vulnerability_id": "CVE-456"
        }
    ],
    "package4": [
        {
            "cvss_v2_score": 0.0,
            "cvss_v30_score": 0.0,
            "cvss_v31_score": 9.1,
            "cvss_v3_score": 9.1,
            "cvss_v3_severity": "CRITICAL",
            "description": "temp-description",
            "name": "CVE-456",
            "package_details": {
                "file_path": "usr/lib",
                "name": "package4",
                "package_manager": "PYTHONPKG",
                "release": null,
                "version": "1.2"
            },
            "package_name": "package4",
            "remediation": {
                "recommendation": {
                    "text": "None Provided"
                }
            },
            "severity": "CRITICAL",
            "source": "SNYK",
            "source_url": "https://temp-url",
            "status": "ACTIVE",
            "title": "CVE-456 - package2/package4",
            "vulnerability_id": "CVE-456"
        }
    ]
}