{
    "org.apache.ant:ant": [
        {
            "description": "As mitigation for CVE-2020-1945 Apache Ant 1.10.8 changed the permissions of temporary files it created so that only the current user was allowed to access them. Unfortunately the fixcrlf task deleted the temporary file and created a new one without said protection, effectively nullifying the effort. This would still allow an attacker to inject modified source files into the build process.",
            "vulnerability_id": "CVE-2020-11979",
            "name": "CVE-2020-11979",
            "package_name": "org.apache.ant:ant",
            "package_details": {
                "file_path": "opt/conda/libnvvp/plugins/org.apache.ant_1.9.2.v201404171502/lib/ant.jar",
                "name": "org.apache.ant:ant",
                "package_manager": "JAR",
                "version": "1.9.2",
                "release": null
            },
            "remediation": {
                "recommendation": {
                    "text": "None Provided"
                }
            },
            "cvss_v3_score": 7.5,
            "cvss_v30_score": 0.0,
            "cvss_v31_score": 7.5,
            "cvss_v2_score": 5.0,
            "cvss_v3_severity": "HIGH",
            "source_url": "https://nvd.nist.gov/vuln/detail/CVE-2020-11979",
            "source": "NVD",
            "severity": "HIGH",
            "status": "ACTIVE",
            "title": "CVE-2020-11979 - org.apache.ant:ant"
        }
    ],
    "torch": [
        {
            "description": "## Overview\n[torch](https://pypi.org/project/torch) is a Tensors and Dynamic neural networks in Python with strong GPU acceleration\n\nAffected versions of this package are vulnerable to Arbitrary Code Injection through `filter-test-configs` in the `pull_request_target-triggered` workflow, allowing an attacker to use a malicious branch name to gain command execution and potentially leak secrets.\r\n\r\n**Mitigation:**\r\n\r\nUse an intermediate environment variable for potentially attacker-controlled values such as `github.event.workflow_run.head_branch`:\r\n\r\n```\r\n- name: Select all requested test configurations\r\n  shell: bash\r\n  env:\r\n    GITHUB_TOKEN: ${{ inputs.github-token }}\r\n    JOB_NAME: ${{ steps.get-job-name.outputs.job-name }}\r\n    HEAD_BRANCH: ${{ github.event.workflow_run.head_branch }}\r\n  id: filter\r\n  run: |\r\n    ...\r\n    python3 \"${GITHUB_ACTION_PATH}/../../scripts/filter_test_configs.py\" \\\r\n      ...\r\n      --branch \"$HEAD_BRANCH\"\r\n```\n## Remediation\nThere is no fixed version for `torch`.\n## References\n-",
            "vulnerability_id": "SNYK-PYTHON-TORCH-5876728",
            "name": "SNYK-PYTHON-TORCH-5876728",
            "package_name": "torch",
            "package_details": {
                "file_path": "opt/conda/lib/python3.10/site-packages/torch-2.0.1-py3.10.egg-info/PKG-INFO",
                "name": "torch",
                "package_manager": "PYTHONPKG",
                "version": "2.0.1",
                "release": null
            },
            "remediation": {
                "recommendation": {
                    "text": "None Provided"
                }
            },
            "cvss_v3_score": 9.8,
            "cvss_v30_score": 0.0,
            "cvss_v31_score": 9.8,
            "cvss_v2_score": 0.0,
            "cvss_v3_severity": "CRITICAL",
            "source_url": "https://security.snyk.io/vuln/SNYK-PYTHON-TORCH-5876728",
            "source": "SNYK",
            "severity": "CRITICAL",
            "status": "ACTIVE",
            "title": "IN1-PYTHON-TORCH-5876728 - torch"
        }
    ],
    "cryptography": [
        {
            "reason_to_ignore": "No fix available. Upstream OpenSSL developers consider this to be low.",
            "description": "Issue summary: Generating excessively long X9.42 DH keys or checking\nexcessively long X9.42 DH keys or parameters may be very slow.\n\nImpact summary: Applications that use the functions DH_generate_key() to\ngenerate an X9.42 DH key may experience long delays.  Likewise, applications\nthat use DH_check_pub_key(), DH_check_pub_key_ex() or EVP_PKEY_public_check()\nto check an X9.42 DH key or X9.42 DH parameters may experience long delays.\nWhere the key or parameters that are being checked have been obtained from\nan untrusted source this may lead to a Denial of Service.\n\nWhile DH_check() performs all the necessary checks (as of CVE-2023-3817),\nDH_check_pub_key() doesn't make any of these checks, and is therefore\nvulnerable for excessively large P and Q parameters.\n\nLikewise, while DH_generate_key() performs a check for an excessively large\nP, it doesn't check for an excessively large Q.\n\nAn application that calls DH_generate_key() or DH_check_pub_key() and\nsupplies a key or parameters obtained from an untrusted sour",
            "vulnerability_id": "CVE-2023-5678",
            "name": "CVE-2023-5678",
            "package_name": "cryptography",
            "package_details": {
                "file_path": "opt/conda/lib/python3.10/site-packages/cryptography-41.0.5.dist-info/METADATA",
                "name": "cryptography",
                "package_manager": "PYTHONPKG",
                "version": "41.0.5",
                "release": null
            },
            "remediation": {
                "recommendation": {
                    "text": "None Provided"
                }
            },
            "cvss_v3_score": 7.5,
            "cvss_v30_score": 0.0,
            "cvss_v31_score": 7.5,
            "cvss_v2_score": 0.0,
            "cvss_v3_severity": "HIGH",
            "source_url": "https://nvd.nist.gov/vuln/detail/CVE-2023-5678",
            "source": "NVD",
            "severity": "HIGH",
            "status": "ACTIVE",
            "title": "CVE-2023-5678 - cryptography"
        }
    ],
    "linux": [
        {
            "description": " An out-of-bounds read vulnerability was found in smbCalcSize in fs/smb/client/netmisc.c in the Linux Kernel. This issue could allow a local attacker to crash the system or leak internal kernel information.",
            "vulnerability_id": "CVE-2023-6606",
            "name": "CVE-2023-6606",
            "package_name": "linux",
            "package_details": {
                "file_path": null,
                "name": "linux",
                "package_manager": "OS",
                "version": "5.4.0",
                "release": "169.187"
            },
            "remediation": {
                "recommendation": {
                    "text": "None Provided"
                }
            },
            "cvss_v3_score": 7.1,
            "cvss_v30_score": 0,
            "cvss_v31_score": 7.1,
            "cvss_v2_score": 0,
            "cvss_v3_severity": "HIGH",
            "source_url": "https://people.canonical.com/~ubuntu-security/cve/2023/CVE-2023-6606.html",
            "source": "UBUNTU_CVE",
            "severity": "HIGH",
            "status": "ACTIVE",
            "title": "CVE-2023-6606 - linux",
            "reason_to_ignore": "N/A"
        },
        {
            "description": "\n It was discovered that the CIFS network file system implementation in\n the Linux kernel did not properly validate the server frame size in\n certain situation, leading to an out-of-bounds read vulnerability. An\n attacker could use this to construct a malicious CIFS image that, when\n operated on, could cause a denial of service (system crash) or possibly\n expose sensitive information.",
            "vulnerability_id": "CVE-2023-6606",
            "name": "CVE-2023-6606",
            "package_name": "linux",
            "package_details": {
                "file_path": null,
                "name": "linux",
                "package_manager": "OS",
                "version": "5.4.0",
                "release": "169.187"
            },
            "remediation": {
                "recommendation": {
                    "text": "None Provided"
                }
            },
            "cvss_v3_score": 7.1,
            "cvss_v30_score": 0,
            "cvss_v31_score": 7.1,
            "cvss_v2_score": 0,
            "cvss_v3_severity": "HIGH",
            "source_url": "https://people.canonical.com/~ubuntu-security/cve/2023/CVE-2023-6606.html",
            "source": "UBUNTU_CVE",
            "severity": "HIGH",
            "status": "ACTIVE",
            "title": "CVE-2023-6606 - linux",
            "reason_to_ignore": "N/A"
        },
        {
            "description": "\n It was discovered that the CIFS network file system implementation in\n the Linux kernel did not properly validate the server frame size in\n certain situation, leading to an out-of-bounds read vulnerability. An\n attacker could use this to construct a malicious CIFS image that, when\n operated on, could cause a denial of service (system crash) or possibly\n expose sensitive information.",
            "vulnerability_id": "CVE-2023-6606",
            "name": "CVE-2023-6606",
            "package_name": "linux",
            "package_details": {
                "file_path": null,
                "name": "linux",
                "package_manager": "OS",
                "version": "5.4.0",
                "release": "170.188"
            },
            "remediation": {
                "recommendation": {
                    "text": "None Provided"
                }
            },
            "cvss_v3_score": 7.1,
            "cvss_v30_score": 0,
            "cvss_v31_score": 7.1,
            "cvss_v2_score": 0,
            "cvss_v3_severity": "HIGH",
            "source_url": "https://people.canonical.com/~ubuntu-security/cve/2023/CVE-2023-6606.html",
            "source": "UBUNTU_CVE",
            "severity": "HIGH",
            "status": "ACTIVE",
            "title": "CVE-2023-6606 - linux",
            "reason_to_ignore": "N/A"
        }
    ]
}