{
    "cryptography": [
        {
            "description": "Issue summary: Processing some specially crafted ASN.1 object identifiers or\ndata containing them may be very slow.\n\nImpact summary: Applications that use OBJ_obj2txt() directly, or use any of\nthe OpenSSL subsystems OCSP, PKCS7/SMIME, CMS, CMP/CRMF or TS with no message\nsize limit may experience notable to very long delays when processing those\nmessages, which may lead to a Denial of Service.\n\nAn OBJECT IDENTIFIER is composed of a series of numbers - sub-identifiers -\nmost of which have no size limit.  OBJ_obj2txt() may be used to translate\nan ASN.1 OBJECT IDENTIFIER given in DER encoding form (using the OpenSSL\ntype ASN1_OBJECT) to its canonical numeric text form, which are the\nsub-identifiers of the OBJECT IDENTIFIER in decimal form, separated by\nperiods.\n\nWhen one of the sub-identifiers in the OBJECT IDENTIFIER is very large\n(these are sizes that are seen as absurdly large, taking up tens or hundreds\nof KiBs), the translation to a decimal number in text may take a very long\ntime.  The time complexity is O(",
            "vulnerability_id": "CVE-2023-2650",
            "name": "CVE-2023-2650",
            "package_name": "cryptography",
            "package_details": {
                "file_path": "opt/conda/lib/python3.8/site-packages/cryptography-40.0.2.dist-info/METADATA",
                "name": "cryptography",
                "package_manager": "PYTHONPKG",
                "version": "40.0.2",
                "release": null
            },
            "remediation": {
                "recommendation": {
                    "text": "None Provided"
                }
            },
            "cvss_v3_score": 7.5,
            "cvss_v30_score": 0,
            "cvss_v31_score": 7.5,
            "cvss_v2_score": 0,
            "cvss_v3_severity": "HIGH",
            "source_url": "https://nvd.nist.gov/vuln/detail/CVE-2023-2650",
            "source": "NVD",
            "severity": "HIGH",
            "status": "ACTIVE",
            "title": "CVE-2023-2650 - cryptography"
        }
    ],
    "scipy": [
        {
            "description": "## Overview\n\nAffected versions of this package are vulnerable to Use After Free via the `Py_FindObjects()` function.\r\n\r\n**Note:**\r\n\r\nAccording to the maintainer, this issue is not to be considered a vulnerability.\n## PoC\n```\r\nvoid f() {\r\n  PyObject *result = PyList_New(1); // <-- new reference returned (line 878)\r\n  assert(result);\r\n  printf(\"%ld\\n\", result->ob_refcnt); // 1\r\n\r\n  PyErr_NoMemory(); // <-- error happens, an exception is thrown (line 890)\r\n  Py_XDECREF(result); // <-- destruction here (line 924)\r\n  printf(\"%ld\\n\", result->ob_refcnt); // 0\r\n\r\n  if (PyErr_Occurred()) {\r\n    Py_XDECREF(result); // <-- use after free here (line 931)\r\n    printf(\"%ld\\n\", result->ob_refcnt); // -1\r\n  }\r\n}\r\n```\n## Remediation\nUpgrade `scipy` to version 1.8.0 or higher.\n## References\n- [GitHub Commit](https://github.com/scipy/scipy/commit/e32fc2329d3dd23298725153c5b2cc7fcd0f14f1)\n- [GitHub Issue](https://github.com/scipy/scipy/issues/14713)\n- [GitHub PR](https://github.com/scipy/scipy/pull/15013)\n- [GitHub Release](http",
            "vulnerability_id": "SNYK-PYTHON-SCIPY-5759266",
            "name": "SNYK-PYTHON-SCIPY-5759266",
            "package_name": "scipy",
            "package_details": {
                "file_path": "opt/conda/lib/python3.10/site-packages/scipy-1.7.3.dist-info/METADATA",
                "name": "scipy",
                "package_manager": "PYTHONPKG",
                "version": "1.7.3",
                "release": null
            },
            "remediation": {
                "recommendation": {
                    "text": "None Provided"
                }
            },
            "cvss_v3_score": 7.3,
            "cvss_v30_score": 0,
            "cvss_v31_score": 7.3,
            "cvss_v2_score": 0,
            "cvss_v3_severity": "HIGH",
            "source_url": "https://security.snyk.io/vuln/SNYK-PYTHON-SCIPY-5759266",
            "source": "SNYK",
            "severity": "HIGH",
            "status": "ACTIVE",
            "title": "IN1-PYTHON-SCIPY-5759266 - scipy"
        }
    ],
    "torch": [
        {
            "description": "## Overview\n[torch](https://pypi.org/project/torch) is a Tensors and Dynamic neural networks in Python with strong GPU acceleration\n\nAffected versions of this package are vulnerable to Arbitrary Code Injection through `filter-test-configs` in the `pull_request_target-triggered` workflow, allowing an attacker to use a malicious branch name to gain command execution and potentially leak secrets.\r\n\r\n**Mitigation:**\r\n\r\nUse an intermediate environment variable for potentially attacker-controlled values such as `github.event.workflow_run.head_branch`:\r\n\r\n```\r\n- name: Select all requested test configurations\r\n  shell: bash\r\n  env:\r\n    GITHUB_TOKEN: ${{ inputs.github-token }}\r\n    JOB_NAME: ${{ steps.get-job-name.outputs.job-name }}\r\n    HEAD_BRANCH: ${{ github.event.workflow_run.head_branch }}\r\n  id: filter\r\n  run: |\r\n    ...\r\n    python3 \"${GITHUB_ACTION_PATH}/../../scripts/filter_test_configs.py\" \\\r\n      ...\r\n      --branch \"$HEAD_BRANCH\"\r\n```\n## Remediation\nThere is no fixed version for `torch`.\n## References\n-",
            "vulnerability_id": "SNYK-PYTHON-TORCH-5876728",
            "name": "SNYK-PYTHON-TORCH-5876728",
            "package_name": "torch",
            "package_details": {
                "file_path": "opt/conda/lib/python3.10/site-packages/torch-1.13.1.dist-info/METADATA",
                "name": "torch",
                "package_manager": "PYTHONPKG",
                "version": "1.13.1",
                "release": null
            },
            "remediation": {
                "recommendation": {
                    "text": "None Provided"
                }
            },
            "cvss_v3_score": 9.8,
            "cvss_v30_score": 0,
            "cvss_v31_score": 9.8,
            "cvss_v2_score": 0,
            "cvss_v3_severity": "CRITICAL",
            "source_url": "https://security.snyk.io/vuln/SNYK-PYTHON-TORCH-5876728",
            "source": "SNYK",
            "severity": "CRITICAL",
            "status": "ACTIVE",
            "title": "IN1-PYTHON-TORCH-5876728 - torch"
        }
    ],
    "opencv-python": [
        {
            "description": "Heap buffer overflow in libwebp in Google Chrome prior to 116.0.5845.187 and libwebp 1.3.2 allowed a remote attacker to perform an out of bounds memory write via a crafted HTML page. (Chromium security severity: Critical)",
            "vulnerability_id": "CVE-2023-4863",
            "name": "CVE-2023-4863",
            "package_name": "opencv-python",
            "package_details": {
                "file_path": "opt/conda/lib/python3.10/site-packages/opencv_python-4.8.1.dist-info/METADATA",
                "name": "opencv-python",
                "package_manager": "PYTHONPKG",
                "version": "4.8.1",
                "release": null
            },
            "remediation": {
                "recommendation": {
                    "text": "None Provided"
                }
            },
            "cvss_v3_score": 8.8,
            "cvss_v30_score": 0,
            "cvss_v31_score": 8.8,
            "cvss_v2_score": 0,
            "cvss_v3_severity": "HIGH",
            "source_url": "https://nvd.nist.gov/vuln/detail/CVE-2023-4863",
            "source": "NVD",
            "severity": "HIGH",
            "status": "ACTIVE",
            "title": "CVE-2023-4863 - opencv-python"
        }
    ]
}